# Generated by Django 3.2.5 on 2021-08-24 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_coin_coin_news'),
    ]

    operations = [
        migrations.CreateModel(
            name='CoinCoinNews',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('coin_id', models.BigIntegerField()),
                ('coinnews_id', models.BigIntegerField()),
            ],
            options={
                'db_table': 'coin_coin_news',
                'managed': False,
            },
        ),
    ]
