# Generated by Django 3.2.5 on 2021-08-24 06:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_coin_coin_newss'),
    ]

    operations = [
        migrations.RenameField(
            model_name='coin',
            old_name='coin_newss',
            new_name='coin_newses',
        ),
    ]
