# Generated by Django 3.2.5 on 2021-08-05 06:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Coin',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('coin_name', models.CharField(blank=True, max_length=100, null=True)),
                ('kr_name', models.CharField(blank=True, max_length=100, null=True)),
                ('ticker', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'coin',
            },
        ),
        migrations.CreateModel(
            name='CoinPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=20)),
                ('low_price', models.DecimalField(decimal_places=2, max_digits=20)),
                ('high_price', models.DecimalField(decimal_places=2, max_digits=20)),
                ('coin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coin_price', to='server.coin')),
            ],
            options={
                'db_table': 'coin_price',
            },
        ),
        migrations.CreateModel(
            name='CoinNews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.IntegerField()),
                ('title', models.CharField(blank=True, max_length=100, null=True)),
                ('content', models.CharField(blank=True, max_length=100, null=True)),
                ('upload_date', models.DateTimeField()),
                ('update_date', models.DateTimeField()),
                ('coin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coin_news', to='server.coin')),
            ],
            options={
                'db_table': 'coin_news',
            },
        ),
    ]
