# Generated by Django 3.2.5 on 2021-08-04 14:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='coin',
            old_name='name',
            new_name='coin_name',
        ),
        migrations.AddField(
            model_name='coin',
            name='kr_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.CreateModel(
            name='Coin_price',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=20)),
                ('low_price', models.DecimalField(decimal_places=2, max_digits=20)),
                ('high_price', models.DecimalField(decimal_places=2, max_digits=20)),
                ('coin_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='server.coin')),
            ],
            options={
                'db_table': 'coin_price',
            },
        ),
        migrations.CreateModel(
            name='Coin_news',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.IntegerField()),
                ('title', models.CharField(blank=True, max_length=100, null=True)),
                ('content', models.CharField(blank=True, max_length=100, null=True)),
                ('upload_date', models.DateTimeField()),
                ('update_date', models.DateTimeField()),
                ('coin_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='server.coin')),
            ],
            options={
                'db_table': 'coin_news',
            },
        ),
    ]
