# Generated by Django 3.2.5 on 2021-08-05 12:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coinprice',
            name='high_price',
        ),
        migrations.RemoveField(
            model_name='coinprice',
            name='low_price',
        ),
    ]
