# Generated by Django 3.2.5 on 2021-08-09 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coinprice',
            name='high',
        ),
        migrations.RemoveField(
            model_name='coinprice',
            name='low',
        ),
        migrations.AddField(
            model_name='coinprice',
            name='day_high',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='coinprice',
            name='day_low',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='coinprice',
            name='hour_high',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='coinprice',
            name='hour_low',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='coinprice',
            name='minute_high',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='coinprice',
            name='minute_low',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='coinprice',
            name='week_high',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='coinprice',
            name='week_low',
            field=models.TextField(blank=True, null=True),
        ),
    ]
