# Generated by Django 3.2.5 on 2021-08-10 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0002_auto_20210810_0011'),
    ]

    operations = [
        migrations.AddField(
            model_name='coinprice',
            name='day_close',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='coinprice',
            name='day_open',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='coinprice',
            name='hour_close',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='coinprice',
            name='hour_open',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='coinprice',
            name='minute_close',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='coinprice',
            name='minute_open',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='coinprice',
            name='week_close',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='coinprice',
            name='week_open',
            field=models.TextField(blank=True, null=True),
        ),
    ]
