# Generated by Django 3.2.5 on 2021-08-11 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0003_auto_20210810_2146'),
    ]

    operations = [
        migrations.AddField(
            model_name='coinprice',
            name='day_change',
            field=models.DecimalField(decimal_places=2, max_digits=20, null=True),
        ),
    ]
