# Generated by Django 3.2.5 on 2021-08-04 15:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0003_auto_20210804_2333'),
    ]

    operations = [
        migrations.CreateModel(
            name='CoinNews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.IntegerField()),
                ('title', models.CharField(blank=True, max_length=100, null=True)),
                ('content', models.CharField(blank=True, max_length=100, null=True)),
                ('upload_date', models.DateTimeField()),
                ('update_date', models.DateTimeField()),
            ],
            options={
                'db_table': 'coin_news',
            },
        ),
        migrations.CreateModel(
            name='CoinPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=20)),
                ('low_price', models.DecimalField(decimal_places=2, max_digits=20)),
                ('high_price', models.DecimalField(decimal_places=2, max_digits=20)),
            ],
            options={
                'db_table': 'coin_price',
            },
        ),
        migrations.RemoveField(
            model_name='coin_price',
            name='coin',
        ),
        migrations.AddField(
            model_name='coin',
            name='ticker',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.DeleteModel(
            name='Coin_news',
        ),
        migrations.DeleteModel(
            name='Coin_price',
        ),
        migrations.AddField(
            model_name='coinprice',
            name='coin',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coin_price', to='server.coin'),
        ),
        migrations.AddField(
            model_name='coinnews',
            name='coin',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coin_news', to='server.coin'),
        ),
    ]
