# Generated by Django 3.2.5 on 2021-08-18 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0004_coinprice_day_change'),
    ]

    operations = [
        migrations.RenameField(
            model_name='coinnews',
            old_name='update_date',
            new_name='release_date',
        ),
        migrations.RemoveField(
            model_name='coinnews',
            name='content',
        ),
        migrations.AddField(
            model_name='coinnews',
            name='link',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='coinnews',
            name='source',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='coinnews',
            name='title',
            field=models.TextField(blank=True, null=True),
        ),
    ]
