# Generated by Django 3.2.5 on 2021-08-18 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0005_auto_20210818_1430'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coinnews',
            name='release_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='coinnews',
            name='upload_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
