# Generated by Django 3.2.5 on 2021-08-24 06:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20210824_1459'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coin',
            name='coin_news',
        ),
    ]
