# Generated by Django 3.2.5 on 2021-08-24 06:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_coincoinnews'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CoinCoinNews',
        ),
    ]
