# Generated by Django 3.2.5 on 2021-08-24 07:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_coincoinnews'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CoinCoinNews',
        ),
    ]
