# Generated by Django 3.2.5 on 2021-08-31 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_alter_coinnews_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='coin',
            name='coin_img',
            field=models.TextField(blank=True, null=True),
        ),
    ]
