# Generated by Django 3.2.5 on 2021-09-05 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_coin_coin_img'),
    ]

    operations = [
        migrations.CreateModel(
            name='CoinCoinNewses',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'coin_coin_newses',
                'managed': False,
            },
        ),
    ]
