# Generated by Django 3.2.5 on 2021-08-24 06:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_auto_20210824_1543'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CoinCoinNews',
        ),
    ]
