# Generated by Django 3.2.5 on 2021-08-24 07:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_coinnews_coin_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coinnews',
            name='coin_id',
        ),
    ]
