# Generated by Django 3.2.5 on 2021-08-24 07:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_auto_20210824_1641'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coinnews',
            name='coin',
        ),
    ]
