# Generated by Django 3.2.5 on 2021-08-24 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_remove_coinnews_coin'),
    ]

    operations = [
        migrations.AddField(
            model_name='coin',
            name='coin_newses',
            field=models.ManyToManyField(to='core.CoinNews'),
        ),
    ]
