# Generated by Django 3.2.5 on 2021-08-24 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_alter_coinnews_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coinnews',
            name='link',
            field=models.TextField(blank=True, null=True, unique=True),
        ),
    ]
